cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    re_path(r"^cart/", include("cart.urls")),
    re_path(r"^orders/", include("orders.urls")),
    path("", include("ecomm.urls", namespace="ecomm")),
    path("accounts/", include("allauth.urls")),
    path("account/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("send_mail.urls")),
    path("search/", include("search.urls")),
    path("filter/", include("filter.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import profile, profile_update

app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile/update/', profile_update, name='profile_update'),

]

users/models.py
from allauth.account.models import EmailAddress
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile',
                                verbose_name=_("User"))
    Genders = (
        (_('М'), _('Male')),
        (_('F'), _('Female')),
    )
    first_name = models.CharField(max_length=128, blank=True,
                                  verbose_name=_("First name"))
    last_name = models.CharField(max_length=128, blank=True,
                                 verbose_name=_("Last name"))
    org = models.CharField(max_length=128, blank=True,
                           verbose_name=_("Organization"))
    telephone = models.CharField(max_length=50, blank=True,
                                 verbose_name=_("Telephone"))
    birthday = models.DateField(null=True, verbose_name=_('BirthDay'))
    mod_date = models.DateTimeField(auto_now=True, error_messages={_('required'): ''},
                                    verbose_name=_('Last modified'))
    sex = models.CharField(max_length=1, choices=Genders, default='M',
                           verbose_name=_("Gender"))
    photo = models.ImageField(upload_to="users_avatar/", verbose_name=_("User image"))

    class Meta:
        verbose_name = _('User Profile')

    def __str__(self):
        return "{}'s profile".format(self.user.__str__())

    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False

    def photo_img(self):
        if self.photo:
            from django.utils.safestring import mark_safe
            return mark_safe(
                u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(
                    self.photo.url))
        else:
            return _('No image')

    photo_img.short_description = _('Image')
    photo_img.allow_tags = True

    image_in_profile = ImageSpecField(source='photo',
                                      processors=[ResizeToFill(400, 400)],
                                      format='JPEG',
                                      options={'quality': 60})

users/forms.py
from django import forms
from .models import UserProfile


class ProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = (
            "first_name",
            "last_name",
            "telephone",
            "photo",
            'sex',
            'birthday',

        )
        widgets = {
            "birthday": forms.DateInput(attrs={'type': 'date'}),
            "telephone": forms.NumberInput(attrs={
                'type': "tel",
                "data-tel-input": "",
                "max-length": 50
            })
        }


class SignupForm(forms.Form):
    def signup(self, request, user):
        user_profile = UserProfile()
        user_profile.user = user
        user.save()
        user_profile.save()

users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from orders.models import Order
from users.forms import ProfileForm
from users.models import UserProfile


@login_required
def profile(request):
    user = request.user
    if user.is_superuser:
        order_list = Order.objects.all()
    else:
        current_user = UserProfile.objects.get(user__pk=user.pk)
        order_list = Order.objects.filter(phone_number=current_user.telephone)
    return render(request, 'profile.html', {'user': user,
                                            'title': _('My Profile'),
                                            'order_list': order_list,
                                            })


@login_required
def profile_update(request):
    user = request.user
    user_profile = get_object_or_404(UserProfile, user=user)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()

            user_profile.telephone = form.cleaned_data['telephone']
            user_profile.birthday = form.cleaned_data['birthday']
            user_profile.sex = form.cleaned_data['sex']
            user_profile.photo = form.cleaned_data['photo']
            user_profile.save()

            return HttpResponseRedirect(reverse('users:profile'))
    else:
        default_data = {'first_name': user.first_name,
                        'last_name': user.last_name,
                        'telephone': user_profile.telephone,
                        'sex': user_profile.sex,
                        'photo': user_profile.photo,
                        'birthday': user_profile.birthday,
                        }
        form = ProfileForm(default_data)

    return render(request, 'profile_update.html', {
        'form': form,
        'user': user,
        'title': 'Update Profile'
    })

users/templates/orders_list.html
 <table class="table table-bordered" id="orders_table" style="text-align: center" >
               <thead class="table-success">
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Phone</th>
                        <th>City</th>
                        <th>Post office</th>
                        <th>Status</th>

                    </tr>
               </thead>
                {% for ord in orders_list %}
                    <tr>
                        <td>{{ ord.id }}</td>
                        <td>{{ ord.first_name }}</td>
                        <td>{{ ord.last_name }}</td>
                        <td>{{ ord.phone_number }}</td>
                        <td>{{ ord.delivery_city }}</td>
                        <td>{{ ord.post_office_number }}</td>
                        <td>{{ ord.paid }}</td>
                    </tr>
                {% endfor %}
            </table>

users/templates/phones.html
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var phoneInputs = document.querySelectorAll('input[data-tel-input]');
    
        var getInputNumbersValue = function (input) {
            // Return stripped input value — just numbers
            return input.value.replace(/\D/g, '');
        }
    
        var onPhonePaste = function (e) {
            var input = e.target,
                inputNumbersValue = getInputNumbersValue(input);
            var pasted = e.clipboardData || window.clipboardData;
            if (pasted) {
                var pastedText = pasted.getData('Text');
                if (/\D/g.test(pastedText)) {
                    // Attempt to paste non-numeric symbol — remove all non-numeric symbols,
                    // formatting will be in onPhoneInput handler
                    input.value = inputNumbersValue;
                    return;
                }
            }
        }
    
        var onPhoneInput = function (e) {
            var input = e.target,
                inputNumbersValue = getInputNumbersValue(input),
                selectionStart = input.selectionStart,
                formattedInputValue = "";
    
            if (!inputNumbersValue) {
                return input.value = "";
            }
    
            if (input.value.length != selectionStart) {
                // Editing in the middle of input, not last symbol
                if (e.data && /\D/g.test(e.data)) {
                    // Attempt to input non-numeric symbol
                    input.value = inputNumbersValue;
                }
                return;
            }
    
            if (["7", "8", "9"].indexOf(inputNumbersValue[0]) > -1) {
                if (inputNumbersValue[0] == "9") inputNumbersValue = "7" + inputNumbersValue;
                var firstSymbols = (inputNumbersValue[0] == "8") ? "8" : "+7";
                formattedInputValue = input.value = firstSymbols + " ";
                if (inputNumbersValue.length > 1) {
                    formattedInputValue += '(' + inputNumbersValue.substring(1, 4);
                }
                if (inputNumbersValue.length >= 5) {
                    formattedInputValue += ') ' + inputNumbersValue.substring(4, 7);
                }
                if (inputNumbersValue.length >= 8) {
                    formattedInputValue += '-' + inputNumbersValue.substring(7, 9);
                }
                if (inputNumbersValue.length >= 10) {
                    formattedInputValue += '-' + inputNumbersValue.substring(9, 11);
                }

            } else if (["3", "0"].indexOf(inputNumbersValue[0]) > -1) {
                if (inputNumbersValue[0] == "0") inputNumbersValue = "38" + inputNumbersValue;
                var firstSymbols = (inputNumbersValue[0] == "0") ? "+380" : "+380";
                formattedInputValue = input.value = firstSymbols + " ";
                if (inputNumbersValue.length > 3) {
                    formattedInputValue += '(' + inputNumbersValue.substring(3, 5);
                }
                if (inputNumbersValue.length >= 6) {
                    formattedInputValue += ') ' + inputNumbersValue.substring(5, 8);
                }
                if (inputNumbersValue.length >= 9) {
                    formattedInputValue += '-' + inputNumbersValue.substring(8, 10);
                }
                if (inputNumbersValue.length >= 11) {
                    formattedInputValue += '-' + inputNumbersValue.substring(10, 12);
                }

                
            } else if (["4"].indexOf(inputNumbersValue[0]) > -1) {
                if (inputNumbersValue[0] == "0") inputNumbersValue = "48" + inputNumbersValue;
                var firstSymbols = (inputNumbersValue[0] == "4") ? "+48" : "+48";
                formattedInputValue = input.value = firstSymbols + " ";
                if (inputNumbersValue.length > 2) {
                    formattedInputValue += '(' + inputNumbersValue.substring(2, 4);
                }
                if (inputNumbersValue.length >= 4) {
                    formattedInputValue += ') ' + inputNumbersValue.substring(4, 7);
                }
                if (inputNumbersValue.length >= 7) {
                    formattedInputValue += '-' + inputNumbersValue.substring(7, 9);
                }
                if (inputNumbersValue.length >= 10) {
                    formattedInputValue += '-' + inputNumbersValue.substring(9, 11);
                }

            } else {
                formattedInputValue = '+' + inputNumbersValue.substring(0, 16);
            }
            input.value = formattedInputValue;
             
        }
        var onPhoneKeyDown = function (e) {
            // Clear input after remove last symbol
            var inputValue = e.target.value.replace(/\D/g, '');
            if (e.keyCode == 8 || e.keyCode == 51 && inputValue.length == 1) {
                e.target.value = "";
            }
        }
        for (var phoneInput of phoneInputs) {
            phoneInput.addEventListener('keydown', onPhoneKeyDown);
            phoneInput.addEventListener('input', onPhoneInput, false);
            phoneInput.addEventListener('paste', onPhonePaste, false);
        }

    })
</script>

users/templates/profile.html
{% extends 'ecomm/base.html' %}
{% load i18n %}
{load account %}
{% load static %}
{% block title %}
    <title>{{ title }}</title>

{% endblock title %}
{% block content %}

<div class="container-lg">
    {% if user.is_authenticated %}
    <a href="{% url 'users:profile_update' %}" class="btn btn-primary"  role="button"
    >{% trans "Update Profile" %}</a>
        | <a href="{% url 'account_email' %}" class="btn btn-primary"  role="button"
    >{% trans "Manage Email" %}</a>
        | <a href="{% url 'account_change_password' %}" class="btn btn-primary"
             role="button" >{% trans "Change Password" %}</a>
        | <a href="{% url 'account_logout' %}" class="btn btn-primary"  role="button"
    >{% trans "Logout" %}</a>
{#        {% if user.is_authenticated %}#}
{#        | <a href="{% url 'users:order_detail' %}"class="btn btn-primary"  role="button" >Orders</a>#}
{#        {% endif %}#}
    {% endif %}
    <h3>{% trans "Welcome" %}, {{ user.username }}.</h3>
        <div class="row">
            <div class="col">
                {% if user.profile.photo %}
                <a href="{{ user.profile.photo.url }}" data-fslightbox="images">
                <img
                  class="img-fluid"
                  src="{{user.profile.image_in_profile.url}} "
                  alt="{% trans "User photo" %}"
                />
                </a>
                {% else %}
                   <a href='#' data-fslightbox="images">
                   <img class="img-fluid"
                        src={% static 'ecomm/images/no_foto.png' %}
                                alt="{% trans "No photo available" %}"/></a>
                {% endif %}
            </div>
            <div class="col">
                <div class="info">
                    <div class="mb-4">
                      <h1 class="title">{% trans "My Profile" %}</h1>
                    </div>
                    <div class="mt-2">
                      <h5 class="text">{% trans "First Name" %}: {{ user.first_name }}</h5>
                       <h5 class="text">{% trans "Last Name" %}: {{ user.last_name }}</h5>
                    </div>
                    <div class="text mt-4">
                      <h2 class="text">{% trans "Information" %}</h2>
                      <li>{% trans "Telephone" %}: {{ user.profile.telephone }} </li>
                      <li>{% trans "Gender" %}: {{ user.profile.sex }} </li>
                      <li>{% trans "Birthday" %}: {{ user.profile.birthday }} </li>

                    </div>
                </div>
            </div>

        <div class="mt-5">
            <br/>
            <h3>{% trans 'Your orders' %}</h3>
        </div>
<table class="table table-bordered" id="orders_table" style="text-align: center" >
        <thead class="table-success">
            <tr>
                <th>{% trans "ID" %}</th>
                <th>{% trans "First Name" %}</th>
                <th>{% trans "Last Name" %}</th>
                <th>{% trans "Phone" %}</th>
                <th>{% trans "City" %}</th>
                <th>{% trans "Post office" %}</th>
                <th>{% trans "Status" %}</th>
            </tr>
        </thead>
        {% for order in order_list %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.first_name }}</td>
                <td>{{ order.last_name }}</td>
                <td>{{ order.phone_number }}</td>
                <td>{{ order.delivery_city }}</td>
                <td>{{ order.post_office_number }}</td>
                <td>{{ order.paid }}</td>
            </tr>
        {% endfor %}
</table>


        </div>
</div>
{% endblock content %}

users/templates/profile_backup.html
{% extends 'ecomm/base.html' %}
{% load i18n %}
{load account %}

{% block title %}{{ current_user.get_short_name }}{% endblock %}
{% block content %}
    <h1>{{ current_user.get_short_name}}</h1>
    <p>
        <a href="{% url 'account_change_password' %}">
            {% trans 'Change password' %}</a> |
        <a href="{% url 'account_email' %}">{% trans 'Change or add E-mail' %}</a>
    </p>
    <p>
        <strong>{% trans 'Username' %}:</strong> {{ current_user.username }}
    </p>
    <p>
        <strong>{% trans 'Email' %}:</strong> {{ current_user.email }}
    </p>
    {% if current_user.first_name or current_user.last_name %}
        <p>
            <strong>{% trans 'Name' %}</strong> {{ current_user.get_full_name }}
        </p>
    {% endif %}

{%endblock content %}

users/templates/profile_update.html
{% extends 'ecomm/base.html' %}
{% load i18n %}
{load account %}
{%load static%}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block content %}
<div class="container-lg">
{% if user.is_authenticated %}
        <a href="{% url 'account_email' %}"class="btn btn-primary"  role="button" >
            {% trans "Manage Email" %}</a>
        | <a href="{% url 'account_change_password' %}"class="btn btn-primary"
             role="button" >{% trans "Change Password" %}</a>
        |
    <a href="{% url 'account_logout' %}" class="btn btn-primary"  role="button"
    >{% trans "Logout" %}</a>
    {% endif %}
<h2>{% trans "Update My Profile" %}</h2>
    <div class="row">
        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="mb-3">
              {% for field in form %}
                   <div class=class="form-label">

                    {{ field.label_tag }}
                    <div class="col-auto">
                        {{ field }}
                    </div>
                    {% if field.help_text %}
                         <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                   </div>

                {% endfor %}
                {% include 'phones.html' %}
              <div class="button-wrapper submit">
                 <input type="submit" class="btn btn-primary" value="Update" />
              </div>
          </div>
       </form>
    </div>
</div>
{% endblock %}