cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecomm/urls.py
from django.urls import path
from . import views

app_name = 'ecomm'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('something/', views.something, name='something'),
    path('category/<slug:slug>/', views.category_page, name='category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    re_path(r"^cart/", include("cart.urls")),
    re_path(r"^orders/", include("orders.urls")),
    path("", include("ecomm.urls", namespace="ecomm")),
    path("accounts/", include("allauth.urls")),
    path("account/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("send_mail.urls")),
    path("search/", include("search.urls")),
    path("filter/", include("filter.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from allauth.utils import get_user_model
from ecomm.models import Product
from django.db.models.signals import m2m_changed, pre_save, post_save

User = get_user_model()


class CartManager(models.Manager):

    def new_or_get(self, request):
        card_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=card_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None, products=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(decimal_places=2, default=0.0, max_digits=100)
    total = models.DecimalField(decimal_places=2, default=0.0, max_digits=100)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    objects = CartManager()

    def __str__(self):
        return str(self.pk)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for product in products:
            total += product.price
            if instance.subtotal != total:
                instance.subtotal = total
                instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


from ecomm.models import Product
from .cart import CartLogic
from .form import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = CartLogic(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('ecomm:product_detail', product_id, product.slug)


def cart_remove(request, product_id):
    cart = CartLogic(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = CartLogic(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "ecomm/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>{% trans "Cart" %}</title>
{% endblock title %}

{% block content %}
    <div class="container-lg">
    <h1>{% trans "Your shopping cart" %}</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{% trans "Image" %}</th>
            <th>{% trans "Product" %}</th>
            <th>{% trans "Quantity" %}</th>
            <th>{% trans "Remove" %}</th>
            <th>{% trans "Unit price" %}</th>
            <th>{% trans "Price" %}</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image_in_main.url }}"
                            alt='{% static 'ecomm/images/no_image.jpg' %}'>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">
                        {% trans "Remove" %}</a></td>
                    <td class="num">₴{{ item.price }}</td>
                    <td class="num">₴{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>{% trans "Total" %}</td>
            <td colspan="4"></td>
            <td class="num">₴{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'ecomm:home' %}" class="button light">{% trans "Continue shopping" %}</a>
        {% if cart|length > 0 %}
        <a href="{% url "order_create" %}" class="button">{% trans "Checkout" %}</a>
        {% endif %}
    </p>
    </div>
{% endblock %}