cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecomm/urls.py
from django.urls import path
from . import views

app_name = 'ecomm'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('something/', views.something, name='something'),
    path('category/<slug:slug>/', views.category_page, name='category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    re_path(r"^cart/", include("cart.urls")),
    re_path(r"^orders/", include("orders.urls")),
    path("", include("ecomm.urls", namespace="ecomm")),
    path("accounts/", include("allauth.urls")),
    path("account/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("send_mail.urls")),
    path("search/", include("search.urls")),
    path("filter/", include("filter.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import profile, profile_update

app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile/update/', profile_update, name='profile_update'),

]

ecomm/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from mptt.models import MPTTModel, TreeForeignKey
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class ProductQuerySet(models.query.QuerySet):

    def active(self):
        return self.filter(available=True)

    def featured(self):
        return self.filter(featured=True, available=True)

    def search(self, query):
        lookups = (Q(name__icontains=query) |
                   Q(description__icontains=query) |
                   Q(slug__icontains=query) |
                   Q(price__icontains=query) |
                   Q(tag__name__icontains=query))
        return self.filter(lookups).distinct()


class ProductManager(models.Manager):

    def get_query_set(self):
        return ProductQuerySet(self.model, using=self._db)

    def active_all(self):
        return self.get_query_set().active()

    def featured(self):
        return self.get_query_set().featured()

    def get_by_id(self, pk):
        qs = self.get_queryset().filter(pk=pk)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_query_set().search(query)


class Category(MPTTModel):
    name = models.CharField(max_length=100, db_index=True, verbose_name=_('Category '
                                                                          'name'))
    slug = models.SlugField(max_length=100, db_index=True, unique=True, verbose_name='URL')
    description = models.TextField(max_length=1000, blank=True,
                                   verbose_name=_('Description'))
    available = models.BooleanField(default=True, verbose_name=_('Published'))
    parent = TreeForeignKey("self", on_delete=models.CASCADE, related_name='children', null=True, blank=True,
                            verbose_name=_('Parent category'))
    image = models.ImageField(upload_to="category/%Y", null=True, blank=True,
                              verbose_name=_("Photo"))

    class MPTTMeta:
        order_insertion_by = ['name']
        # level_attr = 'mptt_level'

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return f'{self.name} | - {self.parent}' if self.parent else self.name

    def get_absolute_url(self):
        return reverse('ecomm:category', args=[self.slug])


class ProductType(models.Model):
    name = models.CharField(max_length=150, db_index=True, verbose_name=_('Product '
                                                                          'Name'))
    available = models.BooleanField(default=True, verbose_name=_('Published'))

    class Meta:
        verbose_name = _('Product Type')
        verbose_name_plural = _('Product Types')

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(max_length=150, db_index=True, verbose_name=_('Name'))

    class Meta:
        verbose_name = _('Product Specification')
        verbose_name_plural = _('Product Specifications')

    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT,
                                     verbose_name=_("Product type"))
    category = models.ForeignKey(Category, on_delete=models.RESTRICT,
                                 verbose_name=_("Category"))
    name = models.CharField(max_length=150, db_index=True, verbose_name=_('Name'))
    slug = models.SlugField(max_length=150, db_index=True, unique=True, verbose_name='URL')
    image = models.ImageField(upload_to="product/%Y", blank=True,
                              verbose_name=_("Photo"))
    description = models.TextField(max_length=1000, blank=True,
                                   verbose_name=_('Description'))
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name=_('Price'))
    quantity = models.IntegerField(verbose_name=_('Quantity'), default=20)
    available = models.BooleanField(default=True, verbose_name=_('Published'))
    featured = models.BooleanField(default=False, verbose_name=_('Featured'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Time created at'))
    uploaded = models.DateTimeField(auto_now=True, verbose_name=_('Time updated at'))
    objects = ProductManager()

    class Meta:
        ordering = ('id',)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ecomm:product_detail', args=[self.id, self.slug])

    def image_img(self):
        if self.image:
            from django.utils.safestring import mark_safe
            return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(self.image.url))
        else:
            return '(No image)'

    image_img.short_description = 'Image'
    image_img.allow_tags = True

    image_in_product = ImageSpecField(source='image',
                                      processors=[ResizeToFill(636, 636)],
                                      format='JPEG',
                                      options={'quality': 60})

    image_in_category = ImageSpecField(source='image',
                                       processors=[ResizeToFill(304, 456)],
                                       format='JPEG',
                                       options={'quality': 60})

    image_in_main = ImageSpecField(source='image',
                                   processors=[ResizeToFill(95, 150)],
                                   format='JPEG',
                                   options={'quality': 60})

    def get_short_description(self):
        if len(self.description) < 40:
            return self.description
        return self.description[:40]

    def get_short_name(self):
        if len(self.name) < 40:
            return self.name
        return self.name[:40]


class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                verbose_name=_("Product"))
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT,
                                      verbose_name=_("Specification"))
    value = models.CharField(max_length=255, verbose_name=_('Value'))

    class Meta:
        verbose_name = _('Product Specification Value')
        verbose_name_plural = _('Product Specifications Values')

    def __str__(self):
        return self.value

ecomm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Password again',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

ecomm/views.py
# from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, ProductSpecificationValue, ProductSpecification
from cart.form import CartAddProductForm
from shop.settings import GOOGLE_MAPS_API_KEY

# from django.views.generic import DetailView, ListView


def homepage(request):
    products = Product.objects.filter(available=True)
    context = {"products": products, "title": "Main page"}

    return render(request, "ecomm/main.html", context=context)


def category_page(request, slug):
    category = Category.objects.get(slug=slug)

    if category.level == 0:
        child_cat = category.children.all()
        context = {"category": category, "child_cat": child_cat}
        return render(request, "ecomm/category_parent.html", context=context)

    else:
        products = category.product_set.all()
        context = {"products": products, "category": category}

        sort = request.GET.get("sort")
        if sort:
            products = category.product_set.all()[: int(sort)]
            context["products"] = products

        return render(request, "ecomm/category_children.html", context=context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    product_spec = ProductSpecification.objects.all()
    product_spec_val = ProductSpecificationValue.objects.all()
    cart_product_form = CartAddProductForm()
    context = {
        "product_spec": product_spec,
        "product_spec_val": product_spec_val,
        "product": product,
        "cart_product_form": cart_product_form,
    }

    return render(request, "ecomm/product.html", context=context)


def feedback(request):
    return render(
        request,
        "ecomm/feedback.html",
        {"title": "Feedback", "myapi": GOOGLE_MAPS_API_KEY},
    )


def something(request):
    return render(request, "ecomm/policy.html", {"title": "Something useful"})


def about(request):
    return render(request, "ecomm/about.html", {"title": "About"})

ecomm/templates/ecomm/about.html
{% extends 'ecomm/base.html' %}
{% load i18n %}


{% block title %}<title>{{ title }}</title>{% endblock title %}
{% block content %}
    {% load breadcrumbs %}
    {% get_breadcrumbs_other title %}

<div class="container-lg pt-2">
    <h1>{% trans "Our graduation project" %}</h1>
</div>

{% endblock %}

ecomm/templates/ecomm/base_menu.html
{% load mptt_tags %}
{% load i18n %}
{% load account %}

<div class="header">
    <div class="mainmenu">
        <div class="logo">
			<a href="/"><li class="logo"></li></a>
        </div>

        <div class="category-wrap">
            <p>{% trans "Catalogue" %}</p>
            <div class="categories">
                {% recursetree category_tree %}
                    <ul class="parent-ul">
                        <li>
                            <a href="{{ node.get_absolute_url}}">{{ node.name }}</a>
                            {% if not node.is_leaf_node %}
                                <ul class="children">
                                    <a href="{{ children.get_absolute_url }}">{{ children }}</a>
                                </ul>
                            {% endif %}
                        </li>
                    </ul>
                {% endrecursetree %}
            </div>
        </div>

        <div class="service-page">
                {% for m in menu %}
                    <p class="item"><a href="/{{ m.url_name }}">{{m.title}}</a></p>
                {% endfor %}
        </div>

        <div class="auto">
            {% block account %}
                {% if request.user.is_authenticated %}
                    <li class="auto">{% trans 'Welcome' %}&nbsp;
                        <a href="{% url 'users:profile' %}">{{ user.username }}</a>
                            <div class="separator"></div>
                        <a href="{% url 'account_logout' %}">{% trans 'Logout' %}</a>
                    </li>
                {% else %}
                    <li class="auto">
                        <a href="{% url 'account_signup' %}">{% trans 'Register' %}</a>
                            <div class="separator"></div>
                        <a href="{% url 'account_login' %}">{% trans 'Login'%}</a>
                    </li>
                {%endif %}
            {% endblock account %}
        </div>
    </div>
</div>

ecomm/templates/ecomm/feedback.html
{% extends 'ecomm/base.html' %}
{% load i18n %}

{% block title %}<title>{{ title }}</title>{% endblock title %}

{% block content %}
    {% load breadcrumbs %}
    {% get_breadcrumbs_other title %}

<div class="container-lg pt-2">
    <h1>{% trans "Find us" %}</h1>

    <iframe width="1000" height="450"
            style="border:0" loading="lazy"
            allowfullscreen src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJxZ5aCIExxkARZAneoD2Z30g&key={{ myapi }}">
    </iframe>

    <h2>{% trans "Mail us" %}</h2>
    <div>
        <span>{% trans "SEND EMAILS" %}</span>
        <div>
            <form action="/send_mail" method="POST" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <div>
                    <span>{% trans "Name" %}</span>
                    <input type="text" class="form-control" name="name" maxlength="40" placeholder="Your Name" required>
                </div>
                 <div>
                    <span>{% trans "Email" %}</span>
                    <input type="email" class="form-control" name="email" maxlength="40" placeholder="Your email" required>
                </div>
                <div>
                    <textarea class="from-control" rows="7" name="message" placeholder="Type your message here.." required></textarea>
                </div>
                <button type="submit">{% trans "Send email" %}</button>
            </form>
            <!--Message from Backend-->
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div>{{ message }}
                        <a href="{% url 'ecomm:feedback' %}"></a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

ecomm/templates/ecomm/footer.html
{% load i18n %}
<hr>
<div class="mt-auto pt-4">
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="bootstrap" viewBox="0 0 118 94">
      <title>{% trans "Bootstrap" %}</title>
      <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
    <symbol id="facebook" viewBox="0 0 16 16">
      <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
    </symbol>
    <symbol id="instagram" viewBox="0 0 16 16">
        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
    </symbol>
    <symbol id="twitter" viewBox="0 0 16 16">
      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
    </symbol>
  </svg>

  <div class="bg-light">
    <div class="container-lg">
      <footer class="pt-5">
        <div class="row">
          <div class="col-6 col-md-2 mb-3">
            <h5>{% trans "Quick links" %}</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="{% url 'ecomm:about' %}" class="nav-link p-0 text-muted">{% trans "About" %}</a>
              </li>
              <li class="nav-item mb-2">
                <a href="{% url 'ecomm:feedback' %}" class="nav-link p-0 text-muted">{% trans "Feedback" %}</a>
              </li>
              <li class="nav-item mb-2">
                  <a href="{% url 'ecomm:something' %}" class="nav-link p-0 text-muted">{% trans "Something" %}</a>
              </li>
            </ul>
          </div>

          <div class="col-6 col-md-2 mb-3"></div>

          <div class="col-6 col-md-2 mb-3"></div>

          <div class="col-md-5 offset-md-1 mb-3">
              <h5>{% trans "Search product" %}</h5>
              {% include 'search_form.html' %}
              <div>
                  <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                      <input name="next" type="hidden" value="{{ redirect_to }}">
                          <label>
                              <select name="language"
                                      title="{% trans "Select language" %}">
                                  {% get_current_language as LANGUAGE_CODE %}
                                  {% get_available_languages as LANGUAGES %}
                                  {% get_language_info_list for LANGUAGES as languages %}
                                  {% for language in languages %}
                                      <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                          {{ language.name_local }} ({{ language.code }})
                                      </option>
                                  {% endfor %}
                              </select>
                          </label>
                      <button type="submit">{% trans "Change" %}</button>
                    </form>
              </div>
          </div>
        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-center py-4 my-4
        border-top">
          <p>{% blocktrans %}© 2022 The Test-Shop, Inc. All rights reserved.
          {% endblocktrans %}</p></div>
        <div>
          <ul class="list-unstyled d-flex justify-content-end py-4 my-4">
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
          </ul>
        </div>
      </footer>
    </div>
  </div>
</div>

ecomm/templates/ecomm/navbar.html
{% load static %}
{% load mptt_tags %}
{% load i18n %}
{% load account %}
{% load cache %}
{% url 'cart:cart_detail' as cart_url %}

{#{% cache 60 navbar%}#}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark nav-fill">
  <div class="container-lg">
    <a class="navbar-brand" href="{% url 'ecomm:home' %}">
      <img src="{% static 'ecomm/images/logo.jpg' %}" width="40" height="40" alt="" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
              <a href="{% url 'ecomm:home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Catalog" %}
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                  {% for c in category_tree %}
                    {% if c.is_root_node %}
                    <li><a class="dropdown-item" href="{{ c.get_absolute_url}}">{{ c.name }}</a></li>
                    {% else %}
                        <ul class="dropdown-submenu-left">
                            <li><a class="dropdown-item" href="{{ c.get_absolute_url}}">{{ c.name }}</a></li>
                        </ul>

                    {% endif %}
                  {% endfor %}
              </ul>
          </li>
          <li class="nav-item">
            {% include 'search_form.html' %}
          </li>

          <li class="nav-image" data-bs-toggle="tooltip" data-bs-placement="bottom"
              title="{% with total_items=cart|length %}
                        {% if cart|length > 0 %}
{%  trans "Your cart" %}:
{% trans "units" %}: {{ total_items }}
{% trans "total price" %}: ₴{{ cart.get_total_price }}
                        {% else %}
{% trans "Your cart is empty" %}.
                        {% endif %}
                     {% endwith %}">
              <a class="nav-link" href="{{ cart_url }}">
                  {% if request.session.counter_items %}
                        {{ request.session.counter_items }}
                           <img class="inline_label" alt="{% trans 'Cart' %}" width="30"
                                height="24"
                                src="{% static 'ecomm/images/shopping_cart_full.svg' %}">
                  {% else %}
                  <img class="inline_label" alt="{% trans 'Cart' %}" width="30"
                       height="24"
                       src="{% static 'ecomm/images/shopping_cart.svg' %}">
                  {% endif %}</a>
          </li>

          {% block account %}
          {% if request.user.is_authenticated %}

          <li class="nav-item">
              <a href="{% url 'users:profile' %}" class="nav-link">{% trans 'Welcome' %}&nbsp;{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_logout' %}" class="nav-link">{% trans 'Logout' %}</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a href="{% url 'account_signup' %}" class="nav-link">{% trans 'Register' %}</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'account_login' %}" class="nav-link">{% trans 'Login'%}</a>
          </li>
          {%endif %}
          {% endblock account %}
        </ul>
      </div>
  </div>
</nav>

{#{% endcache %}#}

ecomm/templates/ecomm/product.html
{% extends 'ecomm/base.html' %}
{% load i18n %}

{% block title %}
    <title>{{ product.name }}</title>
{% endblock %}

{% block content %}
    {% load breadcrumbs %}
    {% get_breadcrumbs_product product %}

<div class="container-lg">
    <div class="row">

            <div class="col">
                <img src="{% if product.image %}{{product.image_in_product.url}}{% endif %}" class="img-fluid">
            </div>
            <div class="col">
                <div class="info">
                    <div class="mb-4">
                        <h1 class="title">{{ product.name }}</h1>
                    </div>
                    <div class="mt-2">
                        <h5 class="text">{% trans "Price" %}: {{ product.price }}</h5>
                        <p class="text">
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {{ cart_product_form }}
                                {% csrf_token %}
                                <input class="btn btn-success" type="submit"
                                       value="{% trans "Add to cart" %}">
                             </form>
                        </p>
                    </div>
                    <div class="text mt-4">
                        <h2 class="text">{% trans "Description" %}</h2>
                        <p>{{ product.description }}</p>
                    </div>
                </div>
            </div>
    </div>
    <div class="col">
    <hr/>
    <h3 class="text">{% trans "Product characteristics" %}:</h3>
        {% for spec in product.productspecificationvalue_set.all %}
            <p>{{ spec.specification }} - {{ spec.value }}</p>
        {% endfor %}
    </div>
</div>


{% endblock %}