cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecomm/urls.py
from django.urls import path
from . import views

app_name = 'ecomm'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('something/', views.something, name='something'),
    path('category/<slug:slug>/', views.category_page, name='category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from ajax_select import urls as ajax_select_urls


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    re_path(r"^cart/", include("cart.urls")),
    re_path(r"^orders/", include("orders.urls")),
    path("", include("ecomm.urls", namespace="ecomm")),
    path("accounts/", include("allauth.urls")),
    path("account/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("send_mail.urls")),
    path("search/", include("search.urls")),
    path("filter/", include("filter.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/breadcrumbs.html
<div class="container-lg pt-2">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>

        {% if breadcrumbs_product %}
            {% for item in breadcrumbs_product %}
            {% if forloop.first %}
            <li class="breadcrumb-item"><a href={% url 'ecomm:category' slug=item.slug %}>{{ item.name }}</a></li>
            {% endif %}
            {% if forloop.last %}
            <li class="breadcrumb-item active" aria-current="page">{{ item.name }}</li>
            {% endif %}
            {% endfor %}
        {% endif %}

        {% if breadcrumbs_category %}
            <li class="breadcrumb-item active" aria-current="page">{{ breadcrumbs_category }}</li>
        {% endif %}

        {% if breadcrumbs_other %}
            <li class="breadcrumb-item active" aria-current="page">{{ breadcrumbs_other }}</li>
        {% endif %}
      </ol>
    </nav>
</div>

templates/sidebar.html
<div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 bg-dark">
    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-decoration-none">
        <span class="fs-5 d-none d-sm-inline">Filters</span>
    </a>

    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
        {% for spec in specification %}
        <li>
            <a href="#submenu{{ forloop.counter }}" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">{{ spec }}</span></a>
            <ul class="collapse show nav flex-column ms-1" id="submenu{{ forloop.counter }}" data-bs-parent="#menu">
                {% if forloop.counter == 1 %}
                {% for s in size %}
                <li class="w-100">
                    <a href="/filter?query={{ s }}&product_type={{ product.category.name }}" class="nav-link px-0"><span class="d-none d-sm-inline">{{ s }}</span></a>
                </li>
                {% endfor %}
                {% endif %}

                {% if forloop.counter == 2 %}
                {% for color in colors %}
                <li class="w-100">
                    <a href="/filter?query={{ сolor }}&product_type={{ product.category.name }}" class="nav-link px-0"><span class="d-none d-sm-inline">{{ color }}</span></a>
                </li>
                {% endfor %}
                {% endif %}

                {% if forloop.counter == 3 %}
                {% for b in brand %}
                <li class="w-100">
                    <a href="/filter?query={{ b }}&product_type={{ product.category.name }}" class="nav-link px-0"><span class="d-none d-sm-inline">{{ b }}</span></a>
                </li>
                {% endfor %}
                {% endif %}

                {% if forloop.counter == 4 %}
                {% for cou in country %}
                <li class="w-100">
                    <a href="/filter?query={{cou}}&product_type={{ product.category.name }}" class="nav-link px-0"><span class="d-none d-sm-inline">{{ cou }}</span></a>
                </li>
                {% endfor %}
                {% endif %}

                {% if forloop.counter == 5 %}
                {% for m in material %}
                <li class="w-100">
                    <a href="/filter?query={{ m }}&product_type={{ product.category.name }}" class="nav-link px-0"><span class="d-none d-sm-inline">{{ m }}</span></a>
                </li>
                {% endfor %}
                {% endif %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>